
import { lessons } from './data/lessons.js';
import { recipes } from './data/recipes.js';
import './styles/main.css';

const nav = [['home','Home'],['lessons','Lessons'],['recipes','Recipes'],['notebook','Chef Notebook'],['about','About'],['contact','Contact']];
const icons = { chef:'♨', note:'✎', leaf:'❦', flame:'🔥', print:'⎙', search:'⌕', arrow:'→' };
const meta = (items) => `<div class="meta">${items.map(i=>`<span>${i}</span>`).join('')}</div>`;
const lessonCard = (l) => `<article class="card lesson-card"><p class="tag">${l.category}</p><h3>${l.title}</h3>${meta([l.difficulty,l.time])}<p>${l.description}</p><button class="link-btn">View Lesson</button></article>`;
const recipeCard = (r) => `<article class="card recipe-card" data-category="${r.category}" data-name="${r.name.toLowerCase()}"><p class="tag">${r.category}</p><h3>${r.name}</h3>${meta([r.difficulty,r.prepTime,r.cookTime,r.yield])}<button class="link-btn">View Recipe</button></article>`;
const list = (items, type='ul') => `<${type}>${items.map(i=>`<li>${i}</li>`).join('')}</${type}>`;
function recipeTemplate(r){return `<article class="template print-card"><div class="template-head"><div><p class="eyebrow">Recipe template</p><h2>${r.name}</h2><p>${r.chefNote}</p></div><span class="big-icon">${icons.print}</span></div>${meta([r.yield,r.prepTime,r.cookTime,r.difficulty])}<div class="template-grid"><div><h3>Ingredients</h3>${list(r.ingredients)}<h3>Professional tips</h3><p>${r.tips}</p><h3>HACCP / food safety</h3><p>${r.safety}</p></div><div><h3>Method</h3>${list(r.method,'ol')}<h3>Common mistakes</h3><p>${r.mistakes}</p><h3>Make-ahead & storage</h3><p>${r.makeAhead} ${r.storage}</p><h3>Plating</h3><p>${r.plating}</p></div></div></article>`}
function lessonTemplate(l){return `<article class="template"><p class="eyebrow">Lesson template</p><h2>${l.title}</h2><div class="template-grid"><div><h3>Learning objective</h3><p>${l.objective}</p><h3>Tools needed</h3>${list(l.tools)}<h3>Materials</h3><p>${l.materials}</p><h3>Written lesson</h3><p>${l.writtenLesson}</p></div><div><h3>Step-by-step practice</h3>${list(l.practice,'ol')}<h3>Chef demonstration notes</h3><p>${l.demoNotes}</p><h3>Common mistakes</h3><p>${l.commonMistakes}</p><h3>Practice assignment</h3><p>${l.assignment}</p><h3>Related recipes</h3><p>${l.relatedRecipes.join(', ')}</p></div></div></article>`}
function render(){document.getElementById('root').innerHTML = `
<header class="site-header"><a class="brand" href="#home"><span>CSR</span><div><strong>Chef Recipe Lessons</strong><small>Chef Scott Stokes</small></div></a><nav class="desktop-nav" aria-label="Primary navigation">${nav.map(([id,label])=>`<button data-scroll="${id}">${label}</button>`).join('')}</nav><button class="menu-btn" aria-label="Open menu">☰</button><div class="mobile-panel"><button class="close-btn" aria-label="Close menu">×</button>${nav.map(([id,label])=>`<button data-scroll="${id}">${label}</button>`).join('')}</div></header>
<main><section id="home" class="hero section reveal"><div class="hero-copy"><p class="eyebrow">Pacific Northwest technique • Classical foundations • Modern hospitality</p><h1>Learn to Cook Like a Chef</h1><p class="lede">Professional cooking lessons, polished recipes, practical kitchen systems, and chef guidance presented with the clarity of a culinary school and the beauty of a recipe magazine.</p><div class="cta-row"><button class="btn primary" data-scroll="lessons">Start Learning ${icons.arrow}</button><button class="btn ghost" data-scroll="recipes">Explore Recipes</button></div></div><div class="hero-card"><div class="plate-orbit"><span></span><span></span><span></span></div><p>Chef's Method</p><h2>Technique first. Season with intention. Plate with purpose.</h2><small>New lessons weekly for home cooks, culinary students, and working cooks.</small></div></section>
<section class="section grid-section reveal"><div><p class="eyebrow">Featured lessons</p><h2>Build real kitchen confidence.</h2></div><div class="card-grid">${lessons.slice(0,3).map(lessonCard).join('')}</div></section>
<section class="section grid-section reveal"><div><p class="eyebrow">Featured recipes</p><h2>Restaurant-quality recipes you can repeat.</h2></div><div class="card-grid">${recipes.slice(0,3).map(recipeCard).join('')}</div></section>
<section class="section split reveal"><div><p class="eyebrow">What you'll learn</p><h2>From fundamentals to composed plates.</h2><ul class="check-list"><li>Knife work, mise en place, seasoning, and sauce logic.</li><li>Classic recipes translated into approachable systems.</li><li>Plating, menu planning, food safety, and kitchen leadership.</li></ul></div><div class="method-panel"><span class="big-icon">${icons.chef}</span><h3>The Chef's Method</h3><p>Observe, organize, cook with controlled heat, taste continuously, and document what worked. Every lesson is designed to become usable muscle memory.</p></div></section>
<section class="quote-section reveal"><blockquote>“Cooking becomes professional when intention replaces guesswork.”</blockquote><p>— Chef Scott Stokes</p></section>
<section id="lessons" class="section reveal"><p class="eyebrow">Lessons</p><h2>Structured culinary training.</h2><div class="pill-row">${['Knife Skills','Mother Sauces','Stocks & Soups','Breakfast & Brunch','Baking Fundamentals','Seafood','Meat Cookery','Vegetables & Seasonal Cooking','Plating & Presentation','Menu Planning'].map(c=>`<span>${c}</span>`).join('')}</div><div class="card-grid">${lessons.map(lessonCard).join('')}</div>${lessonTemplate(lessons[0])}</section>
<section id="recipes" class="section reveal"><p class="eyebrow">Recipe Library</p><h2>Searchable chef-tested recipes.</h2><label class="search"><span>${icons.search}</span><input id="recipeSearch" placeholder="Search recipes" /></label><div class="pill-row filters">${['All','Breakfast','Soups','Sauces','Entrees','Baking','Desserts','Senior Living / Assisted Living','Pacific Northwest','Classical French'].map(c=>`<button class="${c==='All'?'active':''}" data-filter="${c}">${c}</button>`).join('')}</div><div class="card-grid recipe-results">${recipes.map(recipeCard).join('')}</div>${recipeTemplate(recipes[0])}</section>
<section id="notebook" class="section reveal"><p class="eyebrow">Chef Notebook</p><h2>Notes from a working kitchen.</h2><div class="notebook-grid">${['Ingredient studies','Classical techniques','Flavor pairings','Menu development','Costing notes','Kitchen systems','Culinary history'].map((i,idx)=>`<article class="note-card"><span class="big-icon">${icons.note}</span><h3>${i}</h3><p>${['Seasonality, sourcing, and quality cues.','Repeatable technique notes and ratios.','Classic and modern pairing logic.','From idea to balanced seasonal menu.','Yield, waste, labor, and pricing notes.','Prep lists, stations, and service flow.','Context that makes technique meaningful.'][idx]}</p></article>`).join('')}</div></section>
<section id="about" class="section split reveal"><div><p class="eyebrow">About Chef Scott Stokes</p><h2>Professional, warm, and practical culinary guidance.</h2><p>Chef Scott Stokes is a Pacific Northwest chef with over 20 years of experience in professional kitchens. His cooking style is rooted in classical technique, seasonal ingredients, hospitality, and practical kitchen leadership.</p><p>This site teaches cooking in a way that is useful for home cooks, culinary students, and working cooks.</p></div><div class="portrait-card"><span class="big-icon">${icons.leaf}</span><h3>Classical technique. Seasonal Northwest sensibility.</h3></div></section>
<section id="contact" class="section contact reveal"><p class="eyebrow">Contact / Signup</p><h2>Start a private lesson, online class, recipe request, or culinary coaching conversation.</h2><form><input placeholder="Name" aria-label="Name"/><input placeholder="Email" type="email" aria-label="Email"/><select aria-label="Interest"><option>Private cooking lessons</option><option>Online class interest</option><option>Recipe request</option><option>Culinary coaching</option><option>Newsletter signup</option></select><textarea placeholder="Tell Chef Scott what you want to learn" aria-label="Message"></textarea><button class="btn primary" type="button">Submit Interest</button></form></section>
<section class="final-cta"><span class="big-icon">${icons.flame}</span><h2>Cook with confidence, clarity, and craft.</h2><button class="btn primary" data-scroll="contact">Start Learning</button></section></main><footer>© 2026 Chef Recipe Lessons • Built for Chef Scott Stokes</footer>`;
}
render();
document.addEventListener('click', (e)=>{ const s=e.target.closest('[data-scroll]'); if(s){document.getElementById(s.dataset.scroll)?.scrollIntoView({behavior:'smooth'}); document.querySelector('.mobile-panel')?.classList.remove('show')} if(e.target.closest('.menu-btn')) document.querySelector('.mobile-panel')?.classList.add('show'); if(e.target.closest('.close-btn')) document.querySelector('.mobile-panel')?.classList.remove('show'); const f=e.target.closest('[data-filter]'); if(f){document.querySelectorAll('[data-filter]').forEach(b=>b.classList.remove('active')); f.classList.add('active'); filterRecipes(); }});
document.addEventListener('input', (e)=>{ if(e.target.id==='recipeSearch') filterRecipes(); });
function filterRecipes(){ const active=document.querySelector('[data-filter].active')?.dataset.filter || 'All'; const q=document.getElementById('recipeSearch')?.value.toLowerCase() || ''; document.querySelectorAll('.recipe-results .recipe-card').forEach(card=>{ const okCat=active==='All'||card.dataset.category===active; const okText=card.dataset.name.includes(q); card.style.display=okCat&&okText?'block':'none'; }); }
